#!/usr/bin/env python
"""Off-policy mismatch probe for the FH-DCMPO TD(lambda) cost target.

Question this instrument answers (diagnosis only -- it changes nothing about training):
**are the L=64 TD(lambda) cost windows realized under behavior policies too different from the
current policy for the cost critic's tail to be calibrated online?**

The replay buffer stores no behavior log-probs, and they cannot be reconstructed exactly (the
policy changes every iteration; checkpoints exist every 5k). What checkpoints DO allow is an
exact emulation: roll out checkpoint ``pi_old`` (the behavior policy a replay transition of age
``delta`` was generated by), then evaluate everything under checkpoint ``pi_new`` (the current
policy). Both densities are exact -- nothing is faked.

Phases (cached to disk between them):

1. ``rollout``  -- roll out every checkpoint stochastically, recording obs/actions/log-probs/costs.
2. ``mismatch`` -- per-depth ``log_ratio_j = log pi_new(a_j|s_j) - log pi_behavior(a_j|s_j)``
   along 64-step windows, cumulative products, ESS, extreme-ratio fractions, and the correlation
   with window cost (report section 2 of the investigation).
3. ``calib``    -- pi_new's cost critic evaluated on states/actions/realized cost-to-go from each
   age bucket (report section 3: does calibration degrade specifically on old-policy data?).
4. ``control``  -- retrain ONLY the cost critic from the pi_new checkpoint, same TD(lambda) rule,
   same update count, on (a) an age-mixed buffer emulating full replay vs (b) recent-only data;
   evaluate both on held-out pi_new rollouts (report section 4: the causal control).

Usage (defaults match the live a2_lag_cc4 run):
    CUDA_VISIBLE_DEVICES=1 python scripts/analysis/offpolicy_mismatch_probe.py \
        --run_dir logs/safety_gymnasium/SafetyPointGoal1-v0/FHDCMPO/20260819_080249 \
        --config config/safety_gymnasium_fhdcmpo_a2_lag_cc4_60k.yaml --phase all
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from copy import deepcopy
from pathlib import Path

import numpy as np
import torch
import yaml

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts" / "eval"))

from eval_safety_gymnasium import load_train_cfg, obs_shaping_env_kwargs, parse_cost_limits  # noqa: E402

from safe_rl.common.fh_cost import quantile_cvar, quantile_var  # noqa: E402
from safe_rl.envs import make_env  # noqa: E402
from safe_rl.modules.critic import quantile_huber_loss  # noqa: E402
from safe_rl.runners import OffPolicyRunner  # noqa: E402
from safe_rl.storage.replay_storage import ReplayStorage  # noqa: E402

DEPTHS = (1, 10, 25, 35, 50, 63)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_dir", required=True, help="run directory holding model_<iter>.pt checkpoints")
    ap.add_argument("--config", required=True)
    ap.add_argument("--env_id", default="SafetyPointGoal1-v0")
    ap.add_argument("--cost_limits", default="25.0")
    ap.add_argument("--num_envs", type=int, default=8)
    ap.add_argument("--episodes", type=int, default=20, help="rollout episodes per checkpoint")
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--seed", type=int, default=777)
    ap.add_argument("--alpha", type=float, default=0.9)
    ap.add_argument("--stride", type=int, default=25, help="calibration state subsampling stride")
    ap.add_argument("--window", type=int, default=64)
    ap.add_argument("--phase", default="all", choices=["rollout", "mismatch", "calib", "control", "all"])
    ap.add_argument("--control_updates", type=int, default=20000, help="cost-critic grad steps per arm")
    ap.add_argument("--control_recent_ckpts", type=int, default=1, help="newest K checkpoints = 'recent' arm")
    ap.add_argument("--out_dir", default="logs/opd_probe")
    return ap.parse_args()


def find_checkpoints(run_dir: Path) -> list[tuple[int, Path]]:
    cks = sorted((int(p.stem.split("_")[1]), p) for p in run_dir.glob("model_*.pt"))
    if len(cks) < 3:
        raise SystemExit(f"need at least 3 checkpoints in {run_dir}, found {len(cks)}")
    return cks


def build_runner(args: argparse.Namespace):
    train_cfg = load_train_cfg(args.config)
    with open(args.config, encoding="utf-8") as fh:
        env_cfg = (yaml.safe_load(fh) or {}).get("env", {}) or {}
    env_kwargs = {"device": args.device, "cost_limits": parse_cost_limits(args.cost_limits), "seed": args.seed}
    env_kwargs.update(obs_shaping_env_kwargs(env_cfg, args.config))
    env = make_env(env_id=args.env_id, num_envs=args.num_envs, **env_kwargs)
    train_cfg.setdefault("runner", {})["max_size"] = 1024  # the probe never uses the runner's buffer
    runner = OffPolicyRunner(env, train_cfg, log_dir=None, device=args.device)
    return env, runner


def load_policy(runner, ckpt: Path):
    """A fresh policy copy carrying this checkpoint's weights (runner's own policy untouched)."""
    state = torch.load(ckpt, weights_only=False, map_location=runner.device)
    pol = deepcopy(runner.actor_critic)
    pol.load_state_dict(state["model_state_dict"], strict=False)
    pol.eval()
    return pol


@torch.inference_mode()
def rollout(env, pol, episodes: int, device: str) -> dict[str, np.ndarray]:
    """Step-major rollout [T, E, ...] with exact behavior log-probs. Episodes are synchronized
    (fixed 1000-step horizon, no random init), matching the training collection layout."""
    n = env.num_envs
    obs, _ = env.reset()
    obs = obs.to(device)
    O, A, LP, C, D = [], [], [], [], []
    done_eps = 0
    while done_eps < episodes:
        a, _ = pol.sample_with_log_prob(obs)
        # Behavior log-prob through the SAME atanh-inversion path the mismatch pass uses, so
        # tanh-saturated actions cancel exactly and delta=0 reads log_ratio == 0 (verified:
        # with the sampled log-prob instead, saturation alone manufactures ~1% "extreme" ratios).
        lp = pol.action_log_prob(obs, a)
        nxt, _, dones, infos = env.step(a)
        costs = infos.get("costs", torch.zeros(n, device=device)).reshape(n, -1).sum(-1)
        O.append(obs.cpu().numpy().astype(np.float32))
        A.append(a.cpu().numpy().astype(np.float32))
        LP.append(lp.reshape(-1).cpu().numpy().astype(np.float32))
        C.append(costs.cpu().numpy().astype(np.float32))
        D.append(dones.reshape(-1).cpu().numpy().astype(np.float32))
        done_eps += int((dones > 0).sum())
        obs = nxt.to(device)
    return {k: np.stack(v) for k, v in zip("oalcd", (O, A, LP, C, D))}


def episode_bounds(d: np.ndarray) -> list[tuple[int, int, int]]:
    """(env, start, end_exclusive) for every COMPLETE episode in step-major dones [T, E]."""
    T, E = d.shape
    out = []
    for e in range(E):
        start = 0
        for t in range(T):
            if d[t, e] > 0:
                out.append((e, start, t + 1))
                start = t + 1
    return out


@torch.inference_mode()
def mismatch_report(data: dict, pol_new, device: str, L: int, out: dict) -> None:
    """Section-2 numbers for one behavior checkpoint's rollouts against pi_new."""
    o, a, lp_b, c, d = (data[k] for k in "oalcd")
    T, E = lp_b.shape
    obs_t = torch.tensor(o.reshape(T * E, -1), device=device)
    act_t = torch.tensor(a.reshape(T * E, -1), device=device)
    lp_n = pol_new.action_log_prob(obs_t, act_t).reshape(T, E).cpu().numpy()
    lr = lp_n - lp_b  # [T, E] per-step log ratio, exact

    flat = lr.reshape(-1)
    out["logratio_mean"] = float(flat.mean())
    out["logratio_median"] = float(np.median(flat))
    out["logratio_p10"] = float(np.quantile(flat, 0.1))
    out["logratio_p90"] = float(np.quantile(flat, 0.9))
    out["frac_ratio_below_half"] = float((flat < -math.log(2)).mean())
    out["frac_ratio_above_2"] = float((flat > math.log(2)).mean())
    out["frac_ratio_extreme"] = float(((flat < -math.log(10)) | (flat > math.log(10))).mean())

    # Windows: every in-episode start with a full L steps ahead; mismatch over offsets 1..L-1
    # (offset 0 is the conditioning action of Q_c(s_t, a_t) -- no mismatch by construction).
    cums, wcosts, ctgs = [], [], []
    for e, s, t_end in episode_bounds(d):
        ep_cost = c[s:t_end, e]
        for w0 in range(s, t_end - L, 8):
            cums.append(lr[w0 + 1 : w0 + L, e].cumsum())
            wcosts.append(ep_cost[w0 - s : w0 - s + L].sum())
            ctgs.append(ep_cost[w0 - s :].sum())
    cums = np.stack(cums)  # [W, L-1]
    wcosts, ctgs = np.asarray(wcosts), np.asarray(ctgs)
    B = cums.shape[0]
    from scipy.special import logsumexp

    for j in DEPTHS:
        col = cums[:, min(j, L - 1) - 1]
        out[f"cum_logratio_mean_j{j}"] = float(col.mean())
        out[f"cum_logratio_p10_j{j}"] = float(np.quantile(col, 0.1))
        out[f"cum_logratio_p90_j{j}"] = float(np.quantile(col, 0.9))
        # ESS/B = (sum w)^2 / (B sum w^2), w = exp(cum log-ratio); log-space, so a 63-step
        # product cannot overflow. 1 = uniform (no correction needed), 1/B = total collapse.
        out[f"ess_frac_j{j}"] = float(np.exp(2 * logsumexp(col) - logsumexp(2 * col)) / B)
    cmag = np.abs(cums[:, -1])
    if cmag.std() > 1e-8:
        if wcosts.std() > 1e-8:
            out["corr_cummismatch_windowcost"] = float(np.corrcoef(cmag, wcosts)[0, 1])
        if ctgs.std() > 1e-8:
            out["corr_cummismatch_costtogo"] = float(np.corrcoef(cmag, ctgs)[0, 1])
    out["n_windows"] = B


@torch.inference_mode()
def calibration_report(data: dict, critic, pol_for_obs_norm, device: str, alpha: float, stride: int, out: dict) -> None:
    """Section-3 numbers: the reference critic on THIS checkpoint's visitation + realized cost-to-go."""
    o, a, _, c, d = (data[k] for k in "oalcd")
    thetas, realized = [], []
    for e, s, t_end in episode_bounds(d):
        total = c[s:t_end, e].sum()
        prior = 0.0
        for t in range(s, t_end):
            if (t - s) % stride == 0:
                obs_t = torch.tensor(o[t, e : e + 1], device=device)
                act_t = torch.tensor(a[t, e : e + 1], device=device)
                thetas.append(critic(obs_t, act_t)[0].float().cpu())
                realized.append(total - prior)
            prior += c[t, e]
    th = torch.stack(thetas).sort(dim=-1).values  # [M, Nq]; QR heads are only ~monotone
    rz = torch.tensor(np.asarray(realized, dtype=np.float32))
    pred_mean, real_mean = float(th.mean()), float(rz.mean())
    out["pred_mean"] = pred_mean
    out["real_mean"] = real_mean
    out["level_ratio"] = pred_mean / max(real_mean, 1e-9)
    out["pred_cvar"] = float(quantile_cvar(th.reshape(-1).sort().values, alpha))
    out["real_cvar"] = float(quantile_cvar(rz.sort().values, alpha))
    out["var_coverage"] = float((rz <= quantile_var(th, alpha)).float().mean())
    out["quantile_loss"] = float(quantile_huber_loss(th, rz.unsqueeze(1), tau_hat_for(th.shape[1]), 1.0).mean())
    out["n_states"] = int(th.shape[0])


def tau_hat_for(nq: int) -> torch.Tensor:
    return (torch.arange(nq, dtype=torch.float32) + 0.5) / nq


def fill_storage(storage: ReplayStorage, datas: list[dict], device: str) -> None:
    """Replay recorded step-major rollouts into a ReplayStorage exactly as the runner would."""
    for data in datas:
        o, a, lp, c, d = (data[k] for k in "oalcd")
        T, E = lp.shape
        for t in range(T - 1):
            nxt = o[t + 1]
            storage.add(
                torch.tensor(o[t], device=device),
                torch.tensor(a[t], device=device),
                torch.zeros(E, 1, device=device),
                torch.tensor(d[t], device=device).view(-1, 1),
                torch.tensor(nxt, device=device),
                costs=torch.tensor(c[t], device=device).view(-1, 1),
                bootstrap=torch.tensor(d[t], device=device).view(-1, 1),  # PointGoal1 ends by time limit
            )


def control_arm(name: str, pol_ref, alg_cfg: dict, datas: list[dict], args, eval_data: dict) -> dict:
    """Retrain ONLY the cost critic from pol_ref's weights on `datas`, then evaluate calibration."""
    from safe_rl.algorithms.fhdcmpo import FHDCMPO

    pol = deepcopy(pol_ref)
    cfg = {k: v for k, v in alg_cfg.items() if k != "class_name"}
    cfg["n_step"] = 10
    alg = FHDCMPO(pol, device=args.device, **cfg)

    # fill_storage writes T-1 steps per rollout; size the ring to hold ALL of them so no
    # window is lost to write-head exclusion.
    n_transitions = sum((d["l"].shape[0] - 1) * d["l"].shape[1] for d in datas)
    storage = ReplayStorage(
        num_envs=args.num_envs,
        max_size=n_transitions,
        obs_shape=[datas[0]["o"].shape[-1]],
        action_shape=[datas[0]["a"].shape[-1]],
        device=args.device,
        n_step=10,
        gamma=float(cfg.get("gamma", 0.99)),
        cost_gamma=1.0,
        cost_n_step=args.window,
    )
    fill_storage(storage, datas, args.device)
    storage._initialized = True

    torch.manual_seed(args.seed)
    losses = []
    for step in range(args.control_updates):
        batch = storage.sample(int(cfg.get("batch_size", 256)))
        obs = batch["observations"]
        critic_obs = batch.get("critic_observations", obs)
        loss = alg._update_cost_critic_quantile(
            obs,
            critic_obs,
            batch["actions"],
            batch["costs"],
            batch["dones"],
            batch["next_observations"],
            batch.get("next_critic_observations", batch["next_observations"]),
            bootstrap=batch.get("bootstrap"),
            effective_n_steps=batch.get("effective_n_steps"),
            cost_window_returns=batch["cost_window_returns"],
            cost_window_next_obs=batch["cost_window_next_obs"],
            cost_window_mask=batch["cost_window_mask"],
        )
        losses.append(loss)
        # Online cadence: cost_critic_updates_per_step=4 grads per soft update (see safe_sac update loop).
        if (step + 1) % 4 == 0:
            pol.soft_update_targets(float(cfg.get("tau", 0.005)))

    out: dict = {"arm": name, "n_transitions": n_transitions, "final_loss": float(np.mean(losses[-200:]))}
    calibration_report(
        eval_data, lambda o, a: pol.cost_critics[0](o, a), pol, args.device, args.alpha, args.stride, out
    )
    return out


def main() -> None:
    args = parse_args()
    run_dir = Path(args.run_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    cks = find_checkpoints(run_dir)
    new_iter, new_ckpt = cks[-1]
    print(f"checkpoints: {[i for i, _ in cks]}; reference (pi_new) = {new_iter}")

    torch.manual_seed(args.seed)
    env, runner = build_runner(args)
    cache = out_dir / f"rollouts_{run_dir.name}_ep{args.episodes}.pt"

    if args.phase in ("rollout", "all") and not cache.exists():
        rolls = {}
        for it, ck in cks:
            pol = load_policy(runner, ck)
            rolls[it] = rollout(env, pol, args.episodes, args.device)
            print(
                f"  rolled {args.episodes} eps of iter {it}: mean episodic cost "
                f"{rolls[it]['c'].reshape(-1).sum() / max(rolls[it]['d'].sum(), 1):.1f}"
            )
        # Held-out evaluation set for the control arms (fresh seed so it is not training data).
        env2_kwargs = {"device": args.device, "cost_limits": parse_cost_limits(args.cost_limits), "seed": args.seed + 1}
        with open(args.config, encoding="utf-8") as fh:
            env2_kwargs.update(obs_shaping_env_kwargs((yaml.safe_load(fh) or {}).get("env", {}) or {}, args.config))
        env2 = make_env(env_id=args.env_id, num_envs=args.num_envs, **env2_kwargs)
        rolls["heldout"] = rollout(env2, load_policy(runner, new_ckpt), args.episodes, args.device)
        env2.close()
        torch.save(rolls, cache)
        print(f"cached rollouts -> {cache}")

    rolls = torch.load(cache, weights_only=False, map_location=args.device)
    pol_new = load_policy(runner, new_ckpt)
    results: dict = {"reference_iter": new_iter, "episodes": args.episodes}

    if args.phase in ("mismatch", "all"):
        print("\n== section 2: mismatch vs checkpoint age ==")
        results["mismatch"] = {}
        for it, _ in cks:
            row: dict = {"delta_iters": new_iter - it}
            mismatch_report(rolls[it], pol_new, args.device, args.window, row)
            results["mismatch"][it] = row
            print(
                f"  iter {it} (delta {row['delta_iters']}): per-step lr mean {row['logratio_mean']:+.3f} "
                f"[p10 {row['logratio_p10']:+.3f}, p90 {row['logratio_p90']:+.3f}]  "
                f"ESS@63 {row['ess_frac_j63']:.3f}  extreme {row['frac_ratio_extreme']:.3f}"
            )

    if args.phase in ("calib", "all"):
        print("\n== section 3: pi_new critic calibration by data age ==")
        results["calib"] = {}
        critic = pol_new.cost_critics[0]
        for it, _ in cks:
            row = {"delta_iters": new_iter - it}
            calibration_report(rolls[it], lambda o, a: critic(o, a), pol_new, args.device, args.alpha, args.stride, row)
            results["calib"][it] = row
            print(
                f"  iter {it} (delta {row['delta_iters']}): level {row['level_ratio']:.2f} "
                f"VaR cov {row['var_coverage']:.3f} (want {args.alpha})  "
                f"CVaR pred/real {row['pred_cvar']:.1f}/{row['real_cvar']:.1f}  qloss {row['quantile_loss']:.3f}"
            )

    if args.phase in ("control", "all"):
        print("\n== section 4: control -- full-mix vs recent-only critic retraining ==")
        alg_cfg = dict(load_train_cfg(args.config)["algorithm"])
        train_iters = [i for i, _ in cks]
        recent = train_iters[-args.control_recent_ckpts :]
        mixed = train_iters[-6:] if len(train_iters) >= 6 else train_iters
        # NOTE the deliberate data-budget asymmetry: the recent arm has fewer DISTINCT
        # transitions, exactly as a recent-only replay restriction would online. Update count,
        # critic init, TD(lambda) rule and evaluation set are identical.
        mixed_datas = [rolls[i] for i in mixed]
        recent_datas = [rolls[i] for i in recent]
        results["control"] = [
            control_arm("full_mix", pol_new, alg_cfg, mixed_datas, args, rolls["heldout"]),
            control_arm("recent_only", pol_new, alg_cfg, recent_datas, args, rolls["heldout"]),
        ]
        for row in results["control"]:
            print(
                f"  {row['arm']:12s}: n {row['n_transitions']}  level {row['level_ratio']:.2f}  "
                f"VaR cov {row['var_coverage']:.3f}  CVaR pred/real {row['pred_cvar']:.1f}/{row['real_cvar']:.1f}  "
                f"final loss {row['final_loss']:.3f}"
            )

    env.close()
    out_json = out_dir / f"opd_{run_dir.name}.json"
    with open(out_json, "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2, default=float)
    print(f"\nresults -> {out_json}")


if __name__ == "__main__":
    main()
