runner_class_name: OffPolicyRunner
seed: 1

algorithm:
  class_name: FastSAC
  gamma: 0.97
  tau: 0.125
  actor_lr: 0.0003
  critic_lr: 0.0003
  alpha_lr: 0.0003
  alpha: 0.001
  auto_entropy_tuning: true
  target_entropy: 0.0
  batch_size: 4096
  num_updates_per_step: 8
  policy_frequency: 4
  clipped_double_q: false
  amp: false
  amp_dtype: bf16
  weight_decay: 0.001
  adam_betas: [0.9, 0.999]

policy:
  class_name: SACActorCritic
  actor_type: stochastic
  critic_type: distributional
  num_critics: 2
  actor_obs_normalization: true
  critic_obs_normalization: true
  actor_kwargs:
    hidden_dims: [512, 256, 128]
    activation: silu
    use_layer_norm: true
    zero_init_heads: true
    log_std_squash: tanh
    log_std_min: -5.0
    log_std_max: 0.0
  critic_kwargs:
    num_atoms: 101
    v_min: -20.0
    v_max: 20.0
    network_type: mlp
    network_kwargs:
      hidden_dims: [768, 384, 192]
      activation: silu
      layer_norm: true

runner:
  num_steps_per_env: 1
  max_iterations: 200000
  max_size: 1000000
  start_random_steps: 5000
  update_after: 5000
  update_every: 1
  reward_normalization: true
  reward_normalization_mode: return
  reward_normalization_g_max: 20.0
  save_interval: 10000
  empirical_normalization: false
  experiment_name: safety_gymnasium_fast_sac
  run_name: ""
  logger: tensorboard
  wandb_project: SafeRL
  wandb_entity: uqerh-kit
